server:
  port: ${PORT}

telegram_bot:
  username: ${BOT_NAME}
  token: ${BOT_TOKEN}
  webhook_path: ${BOT_PATH}
giphy:
  key: ${GIPHY_KEY}
openexchangerates:
  key: ${OPEXR_KEY}
unsplash:
  access_key: ${UNSPLASH_KEY}